test: Add dashboard content check and search epochs and blocks tests
cardano-foundation/cf-explorer-frontend pull request #3418
Opened 2024-05-06 15:34 UTC by Luisdzc

## Description

This pr contains new automation test for dashboard feature, like basic content validation and couple of test for the search logic from dashboard, checking proper search redirection and data validation using BlockFrost services

## Checklist before requesting a review

### Issue ticket number and link

- [x] This PR has a valid ticket number or issue: [[link](https://cardanofoundation.atlassian.net/browse/MET-2154)]

### Testing & Validation

- [x] This PR has been tested/validated in Chrome, Firefox, Safari and Brave browsers.
- [x] The code has been tested locally with test coverage match expectations.
- [] Added new Unit/Component testing (if relevant).

### Security

- [x] No secrets are being committed (i.e. credentials, PII)
- [x] This PR does not have any significant security implications

### Code Review

- [x] There is no unused functionality or blocks of commented out code (otherwise, please explain below)
- [x] In addition to this PR, all relevant documentation (e.g. Confluence / README.md file) and architecture diagrams (e.g. Miro) were updated

### Design Review

- [ ] If this PR contains changes to the UI, it has gone through a design review with UX Designer or Product owner.
- [ ] In case PR contains changes to the UI, add some screenshots to notice the differences
---
#### Chrome
##### _Before_

[comment]: <> (Add screenshots)

##### _After_

[comment]: <> (Add screenshots)

#### Safari
##### _Before_

[comment]: <> (Add screenshots)

##### _After_

[comment]: <> (Add screenshots)

#### Responsive
##### _Before_

[comment]: <> (Add screenshots)

##### _After_

[comment]: <> (Add screenshots)

2024-05-07 14:00 UTC, obstar requested changes

2024-05-07 14:00 UTC, obstar commented on playwright/helpers/endpoints.ts
i would refactor some function pairs e.g. GetBlockByNumber and LastBlockData they have common base "/blocks" same for LastEpochData and LastEpochData "/epochs"

2024-05-07 14:00 UTC, obstar commented on playwright/pages/block-detail.page.ts
>    const blockTotalOutput = page.locator('//div[div[div[text()="Total output in ADA"]]]/following-sibling::div');
add one empty line between 13 and 14 line

2024-05-07 14:00 UTC, obstar commented on playwright/tests/e2e/steps/dashboard.steps.ts
> +
remove line 2

2024-05-14 07:55 UTC, obstar requested changes

2024-05-14 07:55 UTC, obstar commented on playwright/helpers/endpoints.ts
> +  static BLOCKS = class {
BLOCKS -> Blocks

2024-05-14 07:55 UTC, obstar commented on playwright/helpers/endpoints.ts
> +  static EPOCHS = class {
EPOCHS -> Epochs

2024-05-14 07:55 UTC, obstar commented on playwright/helpers/endpoints.ts
>    };
public static get Latest() {
				return `${CardanoFoundation.BlockFrost.Blocks.Base}/latest`;
			}

2024-05-14 07:55 UTC, obstar commented on playwright/helpers/endpoints.ts
>    };
public static get Latest() {
				return `${CardanoFoundation.BlockFrost.Epochs.Base}/latest`;
			}

2024-05-14 07:55 UTC, obstar commented on playwright/api/call-blockfrost/blockfrost.api.ts
> +      Endpoint.BlockFrost.EPOCHS.Base + "/latest",
/latest should be in endpoints.ts - why? becasue you want central place to handle endpoints as per comment in endpints.ts

2024-05-14 07:55 UTC, obstar commented on playwright/api/call-blockfrost/blockfrost.api.ts
> +      Endpoint.BlockFrost.BLOCKS.Base + "/latest",
/latest should be in endpoints.ts - why? becasue you want central place to handle endpoints as per comment in endpints.ts

2024-05-15 15:00 UTC, cfuisat commented on playwright/tests/e2e/features/dashboard.feature
> +    Then the user should see tha general dashboard page with all the resume information
tha -> the ( spelling mistake ) , what is resume information means?

2024-05-15 15:00 UTC, cfuisat commented on playwright/tests/e2e/steps/dashboard.steps.ts
> +Then(/^the user should see tha general dashboard page with all the resume information$/, async ({ page }) => {
tha -> the ( spelling mistake )

2024-05-24 08:51 UTC, cfuisat approved these changes

2024-05-24 08:57 UTC, merged