test: MET-2188 add automation test for epoch
cardano-foundation/cf-explorer-frontend pull request #3507
Opened 2024-05-23 08:47 UTC by Sotatek-TaiTruong

## Description

add automation test for epoch

## Checklist before requesting a review

### Issue ticket number and link

- [x] This PR has a valid ticket number or issue: [[link]](https://cardanofoundation.atlassian.net/browse/MET-2188)

### Testing & Validation

- [ ] This PR has been tested/validated in Chrome, Firefox, Safari and Brave browsers.
- [ ] The code has been tested locally with test coverage match expectations.
- [ ] Added new Unit/Component testing (if relevant).

### Security

- [ ] No secrets are being committed (i.e. credentials, PII)
- [ ] This PR does not have any significant security implications

### Code Review

- [ ] There is no unused functionality or blocks of commented out code (otherwise, please explain below)
- [ ] In addition to this PR, all relevant documentation (e.g. Confluence / README.md file) and architecture diagrams (e.g. Miro) were updated

### Design Review

- [ ] If this PR contains changes to the UI, it has gone through a design review with UX Designer or Product owner.
- [ ] In case PR contains changes to the UI, add some screenshots to notice the differences
---
#### Chrome
##### _Before_

<img width="420" alt="image" src="https://github.com/cardano-foundation/cf-explorer-frontend/assets/117699295/4310d959-ff0f-4862-a445-594178c866b9">

##### _After_

[comment]: <> (Add screenshots)

#### Safari
##### _Before_

[comment]: <> (Add screenshots)

##### _After_

[comment]: <> (Add screenshots)

#### Responsive
##### _Before_

[comment]: <> (Add screenshots)

##### _After_

[comment]: <> (Add screenshots)

2024-05-24 08:58 UTC, Luisdzc commented on playwright/pages/epochs.page.ts
> +
Why did you don't put this into the existing epoch-dashboard.page.ts and epoch-detail.page.ts?

2024-06-05 15:15 UTC, Luisdzc requested changes

2024-06-05 15:15 UTC, Luisdzc commented on playwright/pages/epochs-dashboard.page.ts
> +    expect(page.url().includes("/block")).toBe(true);
When we check the redirect behavior to other pages in this case from epochs to block detail page will be nice make and additional but simple validation at least of the block number or block id depending of what the user selects.

So if the user selects the block number and he is redirected to the block detail page besides to check that the user was redirected to that page we should also add a validation about the user was redirected to the selected block detail page by comparing the selected block number with the block number that is displayed in the block detail page.

Besides like this is a validation over the block detail page this and the respective elements/locators should be in the block-detail.page.ts

2024-06-10 14:48 UTC, Luisdzc approved these changes

2024-06-12 08:37 UTC, obstar approved these changes

2024-06-12 14:43 UTC, cfuisat approved these changes

2024-06-13 08:54 UTC, merged