test: MET-2190 add automation test for block
cardano-foundation/cf-explorer-frontend pull request #3549
Opened 2024-06-04 09:00 UTC by Sotatek-TaiTruong

## Description

 Add automation test for block

## Checklist before requesting a review

### Issue ticket number and link

- [x] This PR has a valid ticket number or issue: [[link]](https://cardanofoundation.atlassian.net/browse/MET-2190)

### Testing & Validation

- [ ] This PR has been tested/validated in Chrome, Firefox, Safari and Brave browsers.
- [ ] The code has been tested locally with test coverage match expectations.
- [ ] Added new Unit/Component testing (if relevant).

### Security

- [ ] No secrets are being committed (i.e. credentials, PII)
- [ ] This PR does not have any significant security implications

### Code Review

- [ ] There is no unused functionality or blocks of commented out code (otherwise, please explain below)
- [ ] In addition to this PR, all relevant documentation (e.g. Confluence / README.md file) and architecture diagrams (e.g. Miro) were updated

### Design Review

- [ ] If this PR contains changes to the UI, it has gone through a design review with UX Designer or Product owner.
- [ ] In case PR contains changes to the UI, add some screenshots to notice the differences
---
#### Chrome
##### _Before_

<img width="601" alt="image" src="https://github.com/cardano-foundation/cf-explorer-frontend/assets/117699295/dae83677-e700-400e-b25c-5b12ad655d80">

##### _After_

[comment]: <> (Add screenshots)

#### Safari
##### _Before_

[comment]: <> (Add screenshots)

##### _After_

[comment]: <> (Add screenshots)

#### Responsive
##### _Before_

[comment]: <> (Add screenshots)

##### _After_

[comment]: <> (Add screenshots)

2024-06-05 15:26 UTC, Luisdzc requested changes

2024-06-05 15:26 UTC, Luisdzc commented on playwright/pages/blocks-dashboard.page.ts
> +  //Block detail
As I mentioned in the epochs test this block detail page locators and respective functions that are executed over the block detail page should be in the block-detail.page.ts class

2024-06-05 15:26 UTC, Luisdzc commented on playwright/pages/blocks-dashboard.page.ts
> +  const blocksDetailTrxTableTxhash = page.getByTestId("block.detail.trxTable.txhash");
This locators should be in the block-detail.page.ts class

2024-06-05 15:26 UTC, Luisdzc commented on playwright/pages/blocks-dashboard.page.ts
> +  const checkTransactionsDetail = async () => {
When we check the redirect behavior as mention for the epochs tests we should also make a simple validation that the redirect goes to the respective element, in this case the user selects the transaction hash so when he be redirected we should also compare the selected tx hash is the same that is displayed in the transaction detail page and like mention for epochs test this check is executed over the transaction detail page so this function and respective locator should be in a separated page called transaction-detail.page.ts for example.

2024-06-05 15:26 UTC, Luisdzc commented on playwright/pages/blocks-dashboard.page.ts
> +  const checkAddressDetail = async () => {
Same as above's comment

2024-06-05 15:26 UTC, Luisdzc commented on playwright/pages/blocks-dashboard.page.ts
> +  const checkPoolDetail = async () => {
Same as above's comment

2024-06-10 14:53 UTC, Luisdzc approved these changes

2024-06-12 08:38 UTC, obstar approved these changes

2024-06-12 14:42 UTC, cfuisat approved these changes

2024-06-13 13:38 UTC, merged