test: MET-2227 add automation test for transaction overview
cardano-foundation/cf-explorer-frontend pull request #3653
Opened 2024-06-27 02:58 UTC by tungnguyendinh

## Description

Please include a summary of the changes and a brief description about this PR

## Checklist before requesting a review

### Issue ticket number and link

- [ ] This PR has a valid ticket number or issue: [link]

### Testing & Validation

- [ ] This PR has been tested/validated in Chrome, Firefox, Safari and Brave browsers.
- [ ] The code has been tested locally with test coverage match expectations.
- [ ] Added new Unit/Component testing (if relevant).

### Security

- [ ] No secrets are being committed (i.e. credentials, PII)
- [ ] This PR does not have any significant security implications

### Code Review

- [ ] There is no unused functionality or blocks of commented out code (otherwise, please explain below)
- [ ] In addition to this PR, all relevant documentation (e.g. Confluence / README.md file) and architecture diagrams (e.g. Miro) were updated

### Design Review

- [ ] If this PR contains changes to the UI, it has gone through a design review with UX Designer or Product owner.
- [ ] In case PR contains changes to the UI, add some screenshots to notice the differences
---
#### Chrome
##### _Before_

[comment]: <> (Add screenshots)

##### _After_

[comment]: <> (Add screenshots)

#### Safari
##### _Before_

[comment]: <> (Add screenshots)

##### _After_
![image](https://github.com/cardano-foundation/cf-explorer-frontend/assets/132549582/49d7fdc7-ab3b-4acf-8f39-3712bb063ab6)

[comment]: <> (Add screenshots)

#### Responsive
##### _Before_

[comment]: <> (Add screenshots)

##### _After_

[comment]: <> (Add screenshots)

2024-06-27 03:10 UTC, Sotatek-TaiTruong commented on playwright/pages/transaction-detail.page.ts
>  }
đưa hàm checkAddressDetail vào file address.page.ts

2024-06-27 03:10 UTC, Sotatek-TaiTruong commented on playwright/pages/transaction-overview.page.ts
> +
dùng lại hàm trong epoch.page

2024-06-27 03:10 UTC, Sotatek-TaiTruong commented on playwright/tests/e2e/steps/transactions-overview.steps.ts
> +Then(
click vào Transaction ở tab sao lại là goToEpochsFromSidebar

2024-06-27 03:48 UTC, Sotatek-TaiTruong approved these changes

2024-07-01 12:45 UTC, Luisdzc requested changes

2024-07-01 12:45 UTC, Luisdzc commented on playwright/tests/e2e/steps/transactions-overview.steps.ts
> +    const trxHash = await page.getByTestId("transaction.table.value.txhash#0");
Steps methods should not have interactions over the pages locators, I understand here you are getting the tx hash from the opened widget and then use that Tx hash for the Koios request. 

A better way to handle this is in the previous steps the `when` step where you open the widget of a transaction, in that moment you capture and return the Tx hash that you will use in the `Then` step. 

Keep in mind that interact with locators is just an action of the Pages classes and the Steps just call functions that has the logic with this locators

2024-07-01 12:45 UTC, Luisdzc commented on playwright/tests/e2e/steps/transactions-overview.steps.ts
> +    const transactionsTableValueEpoch = page.getByTestId("transaction.table.value.txhash#0");
Once again is better keep the logic of locators interactions in the respective pages, this code should be encapsulated in a method inside transactionsOverviewPage like open transaction details page by Tx hash or something like that and then you just call that method from here, if you need the value of the TxHash that method should return it.

2024-07-01 12:45 UTC, Luisdzc commented on playwright/tests/e2e/steps/transactions-overview.steps.ts
> +    const transactionsTableValueEpoch = page.getByTestId("transaction.table.value.block#0");
Same as above comment, let's keep locators interactions inside the pages functions and returns the values that you could need in the next steps if need it.

2024-07-01 12:45 UTC, Luisdzc commented on playwright/tests/e2e/steps/transactions-overview.steps.ts
> +  const deatailPageTitle = page.getByTestId("detail.page.title");
Same as above comment and in this case if the validation is over the block details page that page class should have a method that validate this, in that way maybe for future test we can reuse that method.

2024-07-01 12:45 UTC, Luisdzc commented on playwright/tests/e2e/steps/transactions-overview.steps.ts
> +    const transactionsTableValueEpoch = page.getByTestId("transactions.table.value.epoch#0");
let's keep locators interactions inside the pages functions and returns the values that you could need in the next steps if need it.

2024-07-01 12:45 UTC, Luisdzc commented on playwright/tests/e2e/steps/transactions-overview.steps.ts
> +  const deatailPageTitle = page.getByTestId("detail.page.title");
This validation should be executed in the epoch detail page class and here just call the method that executes the validation.

2024-07-01 12:45 UTC, Luisdzc commented on playwright/tests/e2e/steps/transactions-overview.steps.ts
> +    const transactionsTableValueEpoch = page.getByTestId("transaction.table.value.inputAddress#0").first();
let's keep locators interactions inside the pages functions and returns the values that you could need in the next steps if need it.

2024-07-01 12:45 UTC, Luisdzc commented on playwright/tests/e2e/steps/transactions-overview.steps.ts
> +  const deatailPageTitle = page.getByTestId("detail.page.title");
This validation should be executed in the epoch detail page class and here just call the method that executes the validation.

2024-07-01 12:45 UTC, Luisdzc commented on playwright/tests/e2e/features/transaction-overview.feature
> +    Given the user open the info widget of one transaction record in the transactions table of transaction page
You should use And expression avoid double Given expression

2024-07-01 12:45 UTC, Luisdzc commented on playwright/tests/e2e/features/transaction-overview.feature
> +    Given the user open the info widget of one transaction record in transaction web
Again avoid repeat `Given` expression and use `And` expression, besides that this step execute the same action that the step of the previous test where you basically open the widget of a transaction, please keep in mind this I know that maybe in the document I wrote it a bit different but at the end is the same action so we can reuse steps and avoid duplicated code.

2024-07-01 12:45 UTC, Luisdzc commented on playwright/tests/e2e/features/transaction-overview.feature
> +    Given the user opens the info widget of any transaction in the transactions table from widget of transaction
Use `And` expression

2024-07-01 12:45 UTC, Luisdzc commented on playwright/tests/e2e/features/transaction-overview.feature
> +    Given the user opens the info widget of any transaction in the transactions table from widget
Use And expression

2024-07-01 12:45 UTC, Luisdzc commented on playwright/tests/e2e/features/transaction-overview.feature
> +    Given the user opens the info widget of any transaction in the transactions table from widget tab
Use And expression

2024-07-01 12:45 UTC, Luisdzc commented on playwright/tests/e2e/steps/transactions-overview.steps.ts
> +  const transactionDetailFromWidgetDetailViewBtn = page.getByTestId("transaction.detailViewEpoch.viewDetail");
let's keep locators interactions inside the pages functions and returns the values that you could need in the next steps if need it.

2024-07-01 12:45 UTC, Luisdzc commented on playwright/tests/e2e/steps/transactions-overview.steps.ts
> +  const addressDetailProducer = page.getByTestId("transaction.widget.inputAddress");
let's keep locators interactions inside the pages functions and returns the values that you could need in the next steps if need it.

2024-07-01 12:45 UTC, Luisdzc commented on playwright/tests/e2e/steps/transactions-overview.steps.ts
> +  const transactionDetailFromWidgetBySumary = page.getByTestId("transaction.widget.summary");
let's keep locators interactions inside the pages functions and returns the values that you could need in the next steps if need it.

2024-07-01 12:45 UTC, Luisdzc commented on playwright/tests/e2e/steps/transactions-overview.steps.ts
> +  const transactionDetailFromWidgetByUTXO = page.getByTestId("transaction.widget.utxOs");
let's keep locators interactions inside the pages functions and returns the values that you could need in the next steps if need it.

2024-07-01 12:45 UTC, Luisdzc commented on playwright/tests/e2e/steps/transactions-overview.steps.ts
> +    const transactionWidgetTrxSignature = page.getByTestId("transaction.widget.signersInformation");
let's keep locators interactions inside the pages functions and returns the values that you could need in the next steps if need it.

2024-07-09 13:16 UTC, Luisdzc commented on playwright/tests/e2e/features/transaction-overview.feature
> +    And the user open the info widget of one transaction record in the transactions table of transaction page
Steps in line 35, 41, 47, 53 and 59 are the same step, basically open the info widget of the last transaction we can refactor this step name and re use it in the other test so we don't duplicate code.

2024-07-22 09:00 UTC, merged