Test/met 2243 create automation test for pools page
cardano-foundation/cf-explorer-frontend pull request #3719
Opened 2024-07-17 08:10 UTC by Sotatek-TaiTruong

## Description

Please include a summary of the changes and a brief description about this PR

## Checklist before requesting a review

### Issue ticket number and link

- [x] This PR has a valid ticket number or issue: [[link]](https://cardanofoundation.atlassian.net/browse/MET-2243)

### Testing & Validation

- [ ] This PR has been tested/validated in Chrome, Firefox, Safari and Brave browsers.
- [ ] The code has been tested locally with test coverage match expectations.
- [ ] Added new Unit/Component testing (if relevant).

### Security

- [ ] No secrets are being committed (i.e. credentials, PII)
- [ ] This PR does not have any significant security implications

### Code Review

- [ ] There is no unused functionality or blocks of commented out code (otherwise, please explain below)
- [ ] In addition to this PR, all relevant documentation (e.g. Confluence / README.md file) and architecture diagrams (e.g. Miro) were updated

### Design Review

- [ ] If this PR contains changes to the UI, it has gone through a design review with UX Designer or Product owner.
- [ ] In case PR contains changes to the UI, add some screenshots to notice the differences
---
#### Chrome
##### _Before_

![image](https://github.com/user-attachments/assets/02e18671-2b2e-4321-8661-f3290cea3c70)

##### _After_

[comment]: <> (Add screenshots)

#### Safari
##### _Before_

[comment]: <> (Add screenshots)

##### _After_

[comment]: <> (Add screenshots)

#### Responsive
##### _Before_

[comment]: <> (Add screenshots)

##### _After_

[comment]: <> (Add screenshots)

2024-07-18 12:19 UTC, Luisdzc requested changes

2024-07-18 12:19 UTC, Luisdzc commented on playwright/tests/e2e/features/pools.feature
> +
There is multiple tests steps that make the same function like for example:
**Line 14:** Given the user is in the Pools details page of one Pool
**Line 19:** Given the user is in the Pools details site of one Pool
**Line 24:** Given the user is in the Pools details web of one Pool Comment
It is not necessary write different ways of the same step for each test indeed the idea is to reuse steps if is need it, so please take a look to those steps where logic is the same and just reuse them like:
**Line 14:** Given the user is in the Pools details page of one Pool
**Line 19:** Given the user is in the Pools details page of one Pool
**Line 24:** Given the user is in the Pools details page of one Pool

2024-07-22 09:24 UTC, thuyetsato approved these changes

2024-07-22 09:26 UTC, Luisdzc approved these changes

2024-07-22 09:53 UTC, merged