test: MET-2298 Create automation test for native token
cardano-foundation/cf-explorer-frontend pull request #3790
Opened 2024-08-16 10:49 UTC by tungnguyendinh

## Description

Please include a summary of the changes and a brief description about this PR

## Checklist before requesting a review

### Issue ticket number and link

- [ ] This PR has a valid ticket number or issue: [MET-2298]
https://cardanofoundation.atlassian.net/browse/MET-2298

### Testing & Validation

- [ ] This PR has been tested/validated in Chrome, Firefox, Safari and Brave browsers.
- [ ] The code has been tested locally with test coverage match expectations.
- [ ] Added new Unit/Component testing (if relevant).

### Security

- [ ] No secrets are being committed (i.e. credentials, PII)
- [ ] This PR does not have any significant security implications

### Code Review

- [ ] There is no unused functionality or blocks of commented out code (otherwise, please explain below)
- [ ] In addition to this PR, all relevant documentation (e.g. Confluence / README.md file) and architecture diagrams (e.g. Miro) were updated

### Design Review

- [ ] If this PR contains changes to the UI, it has gone through a design review with UX Designer or Product owner.
- [ ] In case PR contains changes to the UI, add some screenshots to notice the differences
---
#### Chrome
##### _Before_

[comment]: <> (Add screenshots)

##### _After_

[comment]: <> (Add screenshots)

#### Safari
##### _Before_

[comment]: <> (Add screenshots)

##### _After_

[comment]: <> (Add screenshots)

#### Responsive
##### _Before_

[comment]: <> (Add screenshots)

##### _After_

[comment]: <> (Add screenshots)

2024-08-27 13:21 UTC, Luisdzc requested changes

2024-08-27 13:21 UTC, Luisdzc commented on playwright/tests/e2e/steps/native-token.steps.ts
> +  const nativeDetailTrxTableValueEpoch = page.getByTestId("token.transaction.epoch#0");
This interaction should be inside the native tokens page and be used from here like a function, the steps should no use the web elements only the native token page class should use them

2024-09-02 09:52 UTC, Luisdzc approved these changes

2024-09-02 09:55 UTC, Sotatek-TaiTruong approved these changes

2024-09-05 09:30 UTC, merged